name: edutrack_application
description: ""

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8  
  lottie: ^3.3.2
  local_auth: 2.2.0
  shared_preferences: ^2.5.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.0
  carousel_slider: ^5.0.0
  firebase_core: ^4.3.0
  firebase_database: ^12.1.1
  firebase_storage: ^13.0.5
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  screenshot: ^2.1.0
  permission_handler: ^11.3.1
  path_provider: ^2.0.14
  share_plus: ^12.0.1
  visibility_detector: 0.4.0+2
  file_saver: ^0.3.1
  csv: ^6.0.0
  universal_html: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  